/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lance_JNI */

#ifndef _Included_lance_JNI
#define _Included_lance_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lance_JNI
 * Method:    saveToLance
 * Signature: (Ljava/lang/String;Lorg/apache/arrow/vector/FieldVector;Lorg/apache/arrow/memory/BufferAllocator;)V
 */
JNIEXPORT void JNICALL Java_lance_JNI_saveToLance
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
