changelog:
  exclude:
    labels:
      - ci
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - documentation
    - title: Performance Improvements 🚀
      labels:
        - performance
    - title: Other Changes
      labels:
        - "*"
