# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: false
reviews:
  profile: assertive
  poem: false
  review_status: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - WIP
      - Draft
    drafts: false
    base_branches:
      - main
