version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - cmake
    - libarrow-dev
    - libarrow-dataset-dev
    - libparquet-dev
    - libarrow-python-dev
    - libprotobuf-dev
  jobs:
    pre_create_environment:
      - sudo apt -y update
      - sudo apt install -y -V ca-certificates lsb-release wget
      - wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
      - sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
      - sudo apt -y update
sphinx:
   configuration: docs/conf.py

python:
  install:
   - requirements: docs/requirements.txt
