# make all status informational -- pass no matter what
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 10%
        informational: true
    patch:
      default:
        target: 50%
        threshold: 10%
        informational: true
