[package]
name = "pylance"
version = "0.1.2"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
description = "python wrapper for lance-rs"
license = "Apache-2.0"
repository = "https://github.com/eto-ai/lance"
readme = "README.md"
rust-version = "1.65"
keywords = [
    "data-format",
    "data-science",
    "machine-learning",
    "apache-arrow",
    "data-analytics"
]
categories = [
    "database-implementations",
    "data-structures",
    "development-tools",
    "science"
]


[lib]
name = "lance"
crate-type = ["cdylib"]

[dependencies]
arrow-array = "31.0"
arrow-data = "31.0"
arrow-schema = "31.0"
chrono = "0.4.23"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
futures = "0.3"
pyo3 = { version = "0.17.3", features = ["extension-module", "abi3-py38"] }
arrow = { version = "31.0.0", features = ["pyarrow"] }

[target.'cfg(target_os = "macos")'.dependencies]
lance = { path = "..", features = ["blas"]}

[target.'cfg(not(target_os = "macos"))'.dependencies]
lance = { path = ".."}


[build-dependencies]
prost-build = "0.11"
