[package]
name = "pylance"
version = "0.1.2"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
description = "python wrapper for lance-rs"
license = "Apache-2.0"
repository = "https://github.com/eto-ai/lance"
readme = "README.md"
rust-version = "1.65"
keywords = [
    "data-format",
    "data-science",
    "machine-learning",
    "apache-arrow",
    "data-analytics"
]
categories = [
    "database-implementations",
    "data-structures",
    "development-tools",
    "science"
]


[lib]
# `#[pymodule]` in lib.rs
name = "lance"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
lance = { path = ".." }
bytes = "1.3"
arrow-arith = "31.0"
arrow-array = "31.0"
arrow-buffer = "31.0"
arrow-cast = "31.0.0"
arrow-data = "31.0"
arrow-ord = "31.0"
arrow-schema = "31.0"
async-recursion = "1.0"
async-trait = "0.1.60"
byteorder = "1.4.3"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"], optional = true }
object_store = { version = "0.5", features = ["aws"] }
pin-project = "1.0"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
url = "2.3"
rand = "0.8.3"
futures = "0.3"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
arrow = { version = "31.0.0", features = ["pyarrow"] }

[build-dependencies]
prost-build = "0.11"
