[project]
name = "pylance"
dependencies = ["pyarrow>=10", "pandas", "numpy"]

[tool.maturin]
python-source = "python"

[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project.optional-dependencies]
tests = [
    "pytest",
]