[package]
name = "lance-bitpacking"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Vendored copy of https://github.com/spiraldb/fastlanes for use in Lance"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
arrayref = "0.3"
paste = "1"
seq-macro = "0.3"

[lints]
workspace = true
