#!/opt/_internal/pipx/venvs/auditwheel/bin/python
#
# Monkey patch to not ship libarrow(*).so in pypi wheels
import sys

from auditwheel.main import main
from auditwheel.policy import _POLICIES as POLICIES

for p in POLICIES:
    p["lib_whitelist"].extend(
        [
            "libarrow.so.900",
            "libarrow_dataset.so.900",
            "libarrow_python.so.900",
            "libparquet.so.900",
        ]
    )

if __name__ == "__main__":
    sys.exit(main())
