#!/opt/_internal/pipx/venvs/auditwheel/bin/python
#
# Monkey patch to not ship libarrow(*).so in pypi wheels
import sys

from auditwheel.main import main
from auditwheel.policy import _POLICIES as POLICIES

ARROW_VERSION = "1000"

for p in POLICIES:
    p["lib_whitelist"].extend(
        [
            f"libarrow.so.{ARROW_VERSION}",
            f"libarrow_dataset.so.{ARROW_VERSION}",
            f"libarrow_python.so.{ARROW_VERSION}",
            f"libparquet.so.{ARROW_VERSION}",
        ]
    )

if __name__ == "__main__":
    sys.exit(main())
