# We create a composite action to be re-used both for testing and for releasing
name: build_wheel
description: "Build a lance wheel"
inputs:
  python-minor-version:
    description: "8, 9, 10"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install macos dependencies"
      uses: ./.github/workflows/build_mac_wheel/install_mac_deps
    - name: Build macos wheels
      uses: pypa/cibuildwheel@v2.8.1
      env:
        CIBW_BUILD: cp3${{ inputs.python-minor-version }}*
      with:
        package-dir: python
        output-dir: python/wheels
