# We create a composite action to be re-used both for testing and for releasing
name: build_wheel
description: "Build a lance wheel"
inputs:
  python-minor-version:
    description: "8, 9, 10, 11"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install macos dependency
      shell: bash
      run: |
        brew install protobuf
    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        command: build
        working-directory: python

