# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright The Lance Authors

[package]
name = "arrow-scalar"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Scalar value representation for Apache Arrow types"
keywords = ["arrow", "scalar", "data-format"]
categories = ["data-structures"]
rust-version.workspace = true

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-data = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
half = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
