# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\nlance.file\"\x82\x02\n\x08Metadata\x12\x19\n\x11manifest_position\x18\x01 \x01(\x04\x12\x15\n\rbatch_offsets\x18\x02 \x03(\x05\x12\x1b\n\x13page_table_position\x18\x03 \x01(\x04\x12;\n\nstatistics\x18\x05 \x01(\x0b\x32\'.lance.file.Metadata.StatisticsMetadata\x1a\x64\n\x12StatisticsMetadata\x12!\n\x06schema\x18\x01 \x03(\x0b\x32\x11.lance.file.Field\x12\x0e\n\x06\x66ields\x18\x02 \x03(\x05\x12\x1b\n\x13page_table_position\x18\x03 \x01(\x04J\x04\x08\x04\x10\x05\",\n\nDictionary\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x0e\n\x06length\x18\x02 \x01(\x03\"\xfe\x02\n\x05\x46ield\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.lance.file.Field.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x11\n\tparent_id\x18\x04 \x01(\x05\x12\x14\n\x0clogical_type\x18\x05 \x01(\t\x12\x10\n\x08nullable\x18\x06 \x01(\x08\x12&\n\x08\x65ncoding\x18\x07 \x01(\x0e\x32\x14.lance.file.Encoding\x12*\n\ndictionary\x18\x08 \x01(\x0b\x32\x16.lance.file.Dictionary\x12\x16\n\x0e\x65xtension_name\x18\t \x01(\t\x12\x31\n\x08metadata\x18\n \x03(\x0b\x32\x1f.lance.file.Field.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"*\n\x04Type\x12\n\n\x06PARENT\x10\x00\x12\x0c\n\x08REPEATED\x10\x01\x12\x08\n\x04LEAF\x10\x02*H\n\x08\x45ncoding\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05PLAIN\x10\x01\x12\x0e\n\nVAR_BINARY\x10\x02\x12\x0e\n\nDICTIONARY\x10\x03\x12\x07\n\x03RLE\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIELD_METADATAENTRY._options = None
  _FIELD_METADATAENTRY._serialized_options = b'8\001'
  _ENCODING._serialized_start=718
  _ENCODING._serialized_end=790
  _METADATA._serialized_start=27
  _METADATA._serialized_end=285
  _METADATA_STATISTICSMETADATA._serialized_start=179
  _METADATA_STATISTICSMETADATA._serialized_end=279
  _DICTIONARY._serialized_start=287
  _DICTIONARY._serialized_end=331
  _FIELD._serialized_start=334
  _FIELD._serialized_end=716
  _FIELD_METADATAENTRY._serialized_start=625
  _FIELD_METADATAENTRY._serialized_end=672
  _FIELD_TYPE._serialized_start=674
  _FIELD_TYPE._serialized_end=716
# @@protoc_insertion_point(module_scope)
