name: Publish protobuf to BSR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout (branch, tag, or SHA)'
        required: false
        default: ''
        type: string

jobs:
  push-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        ref: ${{ inputs.ref || github.ref }}
        fetch-depth: 0
        lfs: true
    - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0
    - uses: bufbuild/buf-push-action@a654ff18effe4641ebea4a4ce242c49800728459 # v1.2.0
      with:
        buf_token: ${{ secrets.BUF_TOKEN }}
