name: Reusable workflow to build linux wheel

on:
  workflow_call:
    inputs:
      python-minor-version:
        required: true
        type: string

jobs:
  build-wheel:
    runs-on: macos-12
    timeout-minutes: 30
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ inputs.python-minor-version }}
    - name: Install dependencies
      run: |
        brew update
        brew install apache-arrow protobuf
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.8.1
      env:
        CIBW_BUILD: cp3${{ python-minor-version }}*
      with:
        package-dir: python
        output-dir: python/wheels
