name: Reusable workflow to build linux wheel

on:
  workflow_call:
    inputs:
      python-minor-version:
        required: true
        type: string

jobs:
  build-wheel:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ inputs.python-minor-version }}
        cache: 'pip'
        cache-dependency-path: 'python/setup.py'
    - name: Build manylinux wheel
      run: ./tools/build_wheel.sh $(echo cp3${{ inputs.python-minor-version }})