name: Run codspeed benchmarks

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dataset:
    timeout-minutes: 30
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/workflows/build_linux_wheel
        with:
          python-minor-version: "10"
      - name: Pip install
        working-directory: python
        run: |
          pip install $(ls target/wheels/*.whl)
      - name: Codspeed benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: pytest python/python/benchmarks/test_dataset_ops.py --codspeed
