name: Lance File Write Read Round Trip Verification
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  run:
    timeout-minutes: 45
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install Build Requirements
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler

      - name: Validate AWS Credentials
        run: |
          if [ -z "${{ secrets.LANCEDB_S3_READER_ACCESS_KEY }}" ] || [ -z "${{ secrets.LANCEDB_S3_READER_SECRET }}" ]; then
            echo "ERROR: AWS credentials are not properly set"
            exit 1
          fi
          echo "AWS credentials validation successful"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          aws-access-key-id: ${{ secrets.LANCEDB_S3_READER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.LANCEDB_S3_READER_SECRET }}
          aws-region: us-east-2

      - name: Prepare Test Environment
        run: |
          BUCKET_NAME="lance-ci-bucket"
          mkdir -p .github/workflows/file_veification/test_files
          aws s3 ls s3://$BUCKET_NAME
          aws s3 cp s3://$BUCKET_NAME .github/workflows/file_verification/test_files --recursive
          ls -l .github/workflows/file_verification/test_files

      - name: Build Lance
        working-directory: ./python
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pyarrow maturin
          maturin develop --release

      - name: Test Lance File Write Read Round Trip
        run: |
          source python/venv/bin/activate
          cd .github/workflows/file_verification
          python test_write_read.py

      - name: Cleanup
        run: |
          rm -rf .github/workflows/file_verification/test_files
          echo "Cleanup completed: Test files removed"
