name: Typo checker
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: "ubuntu-24.04"
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling of the entire repository
      uses: crate-ci/typos@v1.26.0