name: Upload wheels

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  upload-wheel:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Install dependencies
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build and publish
      working-directory: python
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |        
        twine upload wheels/*.whl